def mockup_values():
    return [{
            "id": 0,
            "nome": "Eletricista",
            "categoria": "Eletricista",
            "telefone": "0800.0001",
            "telefone": "joao@email.com",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 1,
            "nome": "Pedreiro",
            "categoria": "Pedreiro",
            "telefone": "0800.0002",
            "telefone": "rafael@email.com",
            # "link_imagem":"https://st.depositphotos.com/1000291/3330/i/600/depositphotos_33303707-stock-photo-construction-mason-worker-bricklayer.jpg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 2,
            "nome": "Padeiro",
            "categoria": "Padeiro",
            "telefone": "0800.0003",
            "telefone": "pedro@email.com",
            # "link_imagem":"https://conteudo.imguol.com.br/c/bol/entretenimento/ca/2016/07/07/8jul2016---padeiro-mario-francisco-dos-santos-exibe-uma-de-suas-delicias-preparadas-na-padaria-santa-tereza-no-centro-de-sao-paulo-1467941686800_300x420.jpg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 3,
            "nome": "Mecânico",
            "categoria": "Mecanico",
            "telefone": "0800.0004",
            "telefone": "vitor@email.com",
            # "link_imagem":"https://sprintec.com.br/wp-content/uploads/2020/11/20-de-dezembro-e-comemorado-o-dia-do-mecanico-5497fef78b4b42b3ce1d80e2eaec919a.jpg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 4,
            "nome": "Encanador",
            "categoria": "Encanador",
            "telefone": "0800.0005",
            "telefone": "marthyna@email.com",
            # "link_imagem":"https://certificadocursosonline.com/wp-content/uploads/2019/09/curso-de-encanador.jpg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 5,
            "nome": "Seguranca",
            "categoria": "Seguranca",
            "telefone": "0800.0006",
            "telefone": "jose@email.com",
            # "link_imagem":"https://www.verzani.com.br/wp-content/uploads/2021/05/banner-seguranca@2x-1024x504.jpg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 6,
            "nome": "Jardineiro",
            "categoria": "Jardineiro",
            "telefone": "0800.0007",
            "telefone": "maria@email.com",
            # "link_imagem":"https://russelservicos.com.br/wp-content/uploads/2016/01/jardineiro-hotelaria_2.jpg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 7,
            "nome": "Domestico",
            "categoria": "Domestico",
            "telefone": "0800.0008",
            "telefone": "lucas@email.com",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 8,
            "nome": "Motorista",
            "categoria": "Motorista",
            "telefone": "0800.0009",
            "telefone": "renata@email.com",
            # "link_imagem":"https://licencesolucoes.com.br/wp-content/uploads/2021/08/como-se-tornar-motorista-de-aplicativo.jpeg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 9,
            "nome": "Cuidador",
            "categoria": "Cuidador",
            "telefone": "0800.0010",
            "telefone": "laura@email.com",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            {
            "id": 10,
            "nome": "Enfermeiro",
            "categoria": "Enfermeiro",
            "telefone": "0800.0011",
            "telefone": "renato@email.com",
            # "link_imagem":"https://editalconcursosbrasil.com.br/wp-content/uploads/2019/04/enfermeiro.jpg",
            "link_imagem": "https://irp-cdn.multiscreensite.com/0c02236a/dms3rep/multi/ep%2Bver.jpeg",
            "contratado": False,
            },
            ]
