# Generated by Django 4.0.3 on 2022-03-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=255)),
                ('categoria', models.CharField(default='', max_length=255)),
                ('telefone', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('link_imagem', models.CharField(default='', max_length=1023)),
                ('contratado', models.BooleanField(default=False)),
            ],
        ),
    ]
